import { randomUUID } from "crypto";
import { mkdir, readdir, readFile, stat, unlink, writeFile } from "fs/promises";
import path from "path";

/**
 * Local temp-file store for uploaded receipts.
 *
 * Intentional: a receipt photo is kept OUT of MinIO until the extraction
 * flow actually saves transactions. The image lives in a project-relative
 * temp dir (an env override points prod at a writable path like /tmp) and
 * is deleted when the flow ends — either the user cancels or the
 * transactions are saved. A stale-file sweep covers hard-closed tabs.
 *
 * The per-call `/* turbopackIgnore: true *​/` comments opt these runtime fs
 * accesses out of Turbopack's output tracing (the dir is env-driven, so
 * statically it looks dynamic); the temp store is runtime-only by design.
 */

const UUID_RE = /^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$/i;

const MIME_BY_EXT: Record<string, string> = {
  ".jpg": "image/jpeg",
  ".jpeg": "image/jpeg",
  ".png": "image/png",
  ".webp": "image/webp",
  ".gif": "image/gif",
  ".heic": "image/heic",
};

export function getReceiptStorageDir(): string {
  const dir = process.env.RECEIPT_TMP_DIR;
  if (dir) return path.resolve(dir);
  return path.join(process.cwd(), ".tmp", "receipts");
}

/** A receipt id is a UUID generated by us — guards path traversal. */
export function isValidReceiptId(id: string): boolean {
  return UUID_RE.test(id);
}

export async function saveReceiptFile(file: File): Promise<{
  id: string;
  filePath: string;
  mimeType: string;
}> {
  const dir = getReceiptStorageDir();
  await mkdir(/* turbopackIgnore: true */ dir, { recursive: true });

  const ext = path.extname(file.name).toLowerCase() || ".jpg";
  const id = randomUUID();
  const filePath = path.join(dir, `${id}${ext}`);
  const buffer = Buffer.from(await file.arrayBuffer());
  await writeFile(/* turbopackIgnore: true */ filePath, buffer);

  return { id, filePath, mimeType: MIME_BY_EXT[ext] || "application/octet-stream" };
}

export async function readReceiptFile(
  id: string
): Promise<{ data: Buffer; fileName: string; mimeType: string } | null> {
  if (!isValidReceiptId(id)) return null;

  const dir = getReceiptStorageDir();
  let entries: string[];
  try {
    entries = await readdir(/* turbopackIgnore: true */ dir);
  } catch {
    return null;
  }

  // Files are named `<id>.<ext>`; support any extension via prefix scan.
  const entry = entries.find((e) => e.startsWith(`${id}.`));
  if (!entry) return null;

  // `entry` comes from readdir (a basename) and `id` is UUID-validated, so a
  // path separator here can only mean an unlinkable name we shouldn't touch.
  if (entry.includes("/") || entry.includes("\\")) return null;

  const data = await readFile(/* turbopackIgnore: true */ path.join(dir, entry));
  const ext = path.extname(entry).toLowerCase();
  return { data, fileName: entry, mimeType: MIME_BY_EXT[ext] || "application/octet-stream" };
}

export async function deleteReceiptFile(id: string): Promise<void> {
  if (!isValidReceiptId(id)) return;

  const dir = getReceiptStorageDir();
  let entries: string[];
  try {
    entries = await readdir(/* turbopackIgnore: true */ dir);
  } catch {
    return;
  }

  for (const entry of entries) {
    if (entry.startsWith(`${id}.`)) {
      await unlink(/* turbopackIgnore: true */ path.join(dir, entry)).catch(() => {});
    }
  }
}

/**
 * Opportunistic sweep of abandoned temp receipts (hard-closed tab, crashed
 * flow, forgotten upload). Called fire-and-forget on each new upload.
 */
export async function cleanupStaleReceipts(maxAgeMs?: number): Promise<number> {
  const maxAge =
    maxAgeMs ?? (Number(process.env.RECEIPT_MAX_AGE_MS) || 24 * 60 * 60 * 1000);

  const dir = getReceiptStorageDir();
  let entries: string[];
  try {
    entries = await readdir(/* turbopackIgnore: true */ dir);
  } catch {
    return 0;
  }

  const now = Date.now();
  let removed = 0;
  for (const entry of entries) {
    if (!UUID_RE.test(entry.split(".")[0])) continue;
    const filePath = path.join(dir, entry);
    try {
      const s = await stat(/* turbopackIgnore: true */ filePath);
      if (now - s.mtimeMs > maxAge) {
        await unlink(/* turbopackIgnore: true */ filePath);
        removed += 1;
      }
    } catch {
      // ignore per-file errors; keep sweeping
    }
  }
  return removed;
}